server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/damai?useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root

    driver-class-name: com.mysql.jdbc.Driver
    http:
      encoding:
        charset: utf-8
        enabled: true
        force: true
  mvc:
    view:
      prefix:
      suffix: .html
mybatis:
  type-aliases-package: com.goods.pojo,com.goods.dao.TShowDao
  mapper-locations: mapper/*Mapper.xml
#分页
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
#solr
  #配置sorl
  spring:
    data:
      solr:
        host: http://localhost:8983/solr