#默认使用配置
spring:
  profiles:
    active: dev

#公共配置与profiles选择无关 mapperLocations指的路径是src/main/resources
mybatis:


  mapper-locations: classpath:mapper/*.xml

---

#开发配置
spring:
  profiles: dev
  datasource:
    url: jdbc:mysql://148.70.68.230:3306/xiaomai?serverTimezone=GMT%2B8
    username: xiaomai
    password: root
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    druid:
      #用于采集web-jdbc关联监控的数据
      web-stat-filter:
        #添加过滤规则
        url-pattern: '/*'
        #排除一些不必要的url
        exclusions: '*.js,*.gif,*.jpg,*.png,*.css,*.ico,/druid/*'
        enabled: true
        #配置profileEnable能够监控单个url调用的sql列表
        profile-enable: true
        #session统计功能
        session-stat-enable: true
        #session-stat-max-count: 2
      stat-view-servlet:
        enabled: true
        url-pattern: /druid/*
        #是否可以重置统计页面
        reset-enable: true
        #控制台管理用户
        login-username: root
        login-password: root
      aop-patterns: com.example.demo.cn.service.*
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

---

spring:
  security:
    basic:
      enabled: ture
    user:
      name: admin
      password: 123456
---
server:
  port: 8080

# actuator监控
management:
  server:
    # 设置监控服务端口
    port: 8081
  health:
    mail:
      enabled: false
  endpoints:
    # 设置端点是否可用 默认只有shutdown可用
    enabled-by-default: true
    web:
      # 设置是否暴露端点 默认只有health和info可见
      exposure:
        # 包括所有端点
        include: "*" # 注意需要添加引号
        # 排除端点
        exclude: shutdown
---
#配置日志
logging:
  #配置日志文件路径
  level:
    xatu.zsl: debug #不同目录下的日志可配置不同级别
    org.springfromework.web: info
    org.hibernate: error
  #采用相对路径方式将日志文件输出到【log\myspringboot.log】SS
  file: log\myspringboot.log

---

spring:
  redis:
    #数据库索引
    database: 0
    host: 127.0.0.1
    port: 6379
    jedis:
      pool:
        #最大连接数
        max-active: 8
        #最大空闲
        max-idle: 8
        #最小空闲
        min-idle: 0
